/* eslint-disable no-console */
/**
 * UPI Payment Intent Utility
 * ─────────────────────────────────────────────────────────────────────────────
 * Builds native `upi://` deep links that open any installed UPI app on Android
 * (GPay, PhonePe, Paytm, BHIM, etc.) and handles the payment return flow.
 *
 * When user completes payment in the UPI app, it calls the pn (payment notice)
 * URL which can be a page on our domain with query params, or we check URL
 * params on visibilitychange (app resumed) / pageshow.
 *
 * UPI deep link spec:
 *   upi://pay?pa=VPA&pn=NAME&am=AMOUNT&cu=INR&tn=NOTE&tr=TXNREF
 */

import { Transaction } from '@/types';
import { parseUPIPayment } from '@/utils/razorpaySync';

export interface UPIPaymentParams {
  /** Payee VPA — the merchant's UPI ID e.g. merchant@upi */
  pa: string;
  /** Payee name shown in UPI app */
  pn: string;
  /** Amount in INR (decimal string) */
  am: number;
  /** Transaction note / memo */
  tn?: string;
  /** Transaction reference — generated by us to track the payment */
  tr?: string;
}

export interface UPIPaymentResult {
  status: 'SUCCESS' | 'FAILURE' | 'PENDING' | 'SUBMITTED';
  transactionId: string;
  transactionRef: string;
  responseCode: string;
  amount: number;
  pa: string;
  pn: string;
  tn: string;
}

/** Storage key to persist pending UPI payment metadata across redirect */
const PENDING_UPI_KEY = 'sw_pending_upi';

/** How long (ms) to keep a pending payment before considering it abandoned */
const PENDING_TTL = 15 * 60 * 1000; // 15 minutes

export interface PendingUPIPayment {
  tr: string; // transaction reference
  pa: string; // payee VPA
  pn: string; // payee name
  am: number; // amount
  tn: string; // note / description
  ts: number; // timestamp millis when initiated
}

/**
 * Build a UPI intent URL.
 * Returns both a upi:// URL (works on Android apps) and a web-intent URL.
 */
export function buildUPIUrl(
  params: UPIPaymentParams,
  scheme?: string
): { upiUrl: string; returnUrl: string; transactionRef: string } {
  const transactionRef = params.tr || `SW${Date.now()}`;
  const returnUrl = `${window.location.origin}${window.location.pathname}?upi_status=SUBMITTED&upi_tr=${transactionRef}&upi_pa=${encodeURIComponent(params.pa)}&upi_pn=${encodeURIComponent(params.pn)}&upi_am=${params.am}&upi_tn=${encodeURIComponent(params.tn || '')}`;

  const upiParams = new URLSearchParams({
    pa: params.pa,
    pn: params.pn,
    am: String(params.am.toFixed(2)),
    cu: 'INR',
    tn: params.tn || `Payment to ${params.pn}`,
    tr: transactionRef,
    url: returnUrl, // merchant callback (not all apps support this)
    mc: '0000', // merchant category code — generic
  });

  const baseUrl = scheme || 'upi://pay';
  const upiUrl = `${baseUrl}?${upiParams.toString()}`;
  return { upiUrl, returnUrl, transactionRef };
}

/**
 * Save pending payment to localStorage so we can retrieve it
 * after the user returns from the UPI app.
 */
export function savePendingUPIPayment(payment: PendingUPIPayment) {
  localStorage.setItem(PENDING_UPI_KEY, JSON.stringify(payment));
}

/** Retrieve and clear the saved pending UPI payment */
export function getPendingUPIPayment(): PendingUPIPayment | null {
  const raw = localStorage.getItem(PENDING_UPI_KEY);
  if (!raw) return null;
  try {
    const p: PendingUPIPayment = JSON.parse(raw);
    if (Date.now() - p.ts > PENDING_TTL) {
      localStorage.removeItem(PENDING_UPI_KEY);
      return null;
    }
    return p;
  } catch {
    // silently ignore — non-critical
    return null;
  }
}

export function clearPendingUPIPayment() {
  localStorage.removeItem(PENDING_UPI_KEY);
}

/**
 * Parse UPI return query parameters from current URL.
 * UPI apps append: Status, txnId, txnRef, responseCode, ApprovalRefNo
 * We also add our own params: upi_status, upi_tr, upi_am, upi_pa, upi_pn, upi_tn
 */
export function parseUPIReturnParams(): UPIPaymentResult | null {
  const sp = new URLSearchParams(window.location.search);

  // Check our own params (appended when we open upi:// with the returnUrl trick)
  const upiStatus = sp.get('upi_status') || sp.get('Status');
  const transactionRef = sp.get('upi_tr') || sp.get('txnRef') || sp.get('txnId') || '';
  const amount = parseFloat(sp.get('upi_am') || '0');
  const pa = sp.get('upi_pa') || sp.get('pa') || '';
  const pn = sp.get('upi_pn') || sp.get('pn') || '';
  const tn = sp.get('upi_tn') || sp.get('tn') || '';
  const transactionId = sp.get('txnId') || sp.get('ApprovalRefNo') || `upi_${Date.now()}`;
  const responseCode = sp.get('responseCode') || '00';

  // No UPI params at all
  if (!upiStatus && !transactionRef && !sp.get('txnId')) {
    return null;
  }

  const status: UPIPaymentResult['status'] =
    upiStatus === 'SUCCESS' || responseCode === '00'
      ? 'SUCCESS'
      : upiStatus === 'FAILURE'
        ? 'FAILURE'
        : 'PENDING';

  return { status, transactionId, transactionRef, responseCode, amount, pa, pn, tn };
}

/**
 * Convert a UPI payment result into a SpendWise Transaction.
 * Calls AI categorisation for the merchant/note.
 */
export async function upiResultToTransaction(result: UPIPaymentResult): Promise<Transaction> {
  const descForAI = result.tn || result.pn || result.pa;
  const parsed = await parseUPIPayment(descForAI, result.pa);

  return {
    id: `upi_${result.transactionId || result.transactionRef || Date.now()}`,
    date: new Date().toISOString(),
    amount: result.amount,
    type: 'debit',
    category: parsed.category,
    merchant: parsed.merchant || result.pn || result.pa || 'UPI Payment',
    description: result.tn
      ? `UPI · ${result.tn} · Ref: ${result.transactionRef}`
      : `UPI Payment · Ref: ${result.transactionRef}`,
    isNew: true,
    confidence: parsed.confidence,
    aiParsed: parsed.aiParsed,
    tags: ['upi', 'upi-payment'],
  };
}

/**
 * Opens a UPI intent link. On Android it launches the UPI app chooser.
 * On desktop/web it offers a fallback.
 */
export function openUPIIntent(upiUrl: string): void {
  const isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
    navigator.userAgent
  );

  if (isMobile) {
    // Direct redirect is the safest, most robust way on mobile browsers (Chrome, Safari, etc.)
    // It avoids "double intent" triggers and matches browser security policies.
    window.location.href = upiUrl;
  } else {
    // On desktop, try iframe first so we don't navigate to an invalid scheme page
    const iframe = document.createElement('iframe');
    iframe.style.display = 'none';
    iframe.src = upiUrl;
    document.body.appendChild(iframe);
    setTimeout(() => {
      try {
        document.body.removeChild(iframe);
      } catch {
        /* silently ignore — non-critical */
      }
    }, 2000);

    // Fallback if iframe didn't prompt anything
    setTimeout(() => {
      window.location.href = upiUrl;
    }, 500);
  }
}

/**
 * All-in-one: initiate a UPI payment.
 * Saves the pending payment, builds URL, opens intent.
 */
export function initiateUPIPayment(params: UPIPaymentParams, scheme?: string): string {
  const { upiUrl, transactionRef } = buildUPIUrl(params, scheme);

  // Save pending payment for return detection
  savePendingUPIPayment({
    tr: transactionRef,
    pa: params.pa,
    pn: params.pn,
    am: params.am,
    tn: params.tn || '',
    ts: Date.now(),
  });

  // Open UPI app
  openUPIIntent(upiUrl);

  return transactionRef;
}

/** List of common UPI-enabled apps with their deep link app packages (Android) */
export const UPI_APP_INTENTS = [
  {
    id: 'gpay',
    name: 'Google Pay',
    color: '#1a73e8',
    icon: 'G',
    package: 'com.google.android.apps.nbu.paisa.user',
    urlScheme: 'tez://upi/pay',
  },
  {
    id: 'phonepe',
    name: 'PhonePe',
    color: '#5f259f',
    icon: 'P',
    package: 'com.phonepe.app',
    urlScheme: 'phonepe://pay',
  },
  {
    id: 'paytm',
    name: 'Paytm',
    color: '#002970',
    icon: 'T',
    package: 'net.one97.paytm',
    urlScheme: 'paytmmp://pay',
  },
  {
    id: 'bhim',
    name: 'BHIM',
    color: '#f37021',
    icon: 'B',
    package: 'in.org.npci.upiapp',
    urlScheme: 'upi://pay',
  },
  {
    id: 'any',
    name: 'Any UPI App',
    color: '#10b981',
    icon: '₹',
    package: null,
    urlScheme: 'upi://pay',
  },
] as const;

/**
 * P2P Verification Strategy (No Backend Required)
 *
 * Since UPI intents (`upi://pay`) do not securely report back success to a web app,
 * and we don't have a merchant backend to receive Razorpay/Cashfree webhooks,
 * the only secure way to verify a P2P payment occurred on the device is by
 * reading the bank's SMS confirmation ("Debited Rs. 500").
 *
 * Future Implementation: WebOTP API or a React Native / Capacitor plugin.
 */
export async function verifyPaymentViaSMS(
  _expectedAmount: number,
  _expectedRef: string
): Promise<boolean> {
  // Check if WebOTP API is available
  if ('OTPCredential' in window) {
    try {
      console.info('[UPI] Waiting for Bank SMS via WebOTP API...');
      // Note: WebOTP requires the SMS to end with `@ourdomain.com #12345`
      // which banks do not send. So WebOTP only works if the app has native SMS read permissions.
      // In a PWA, this is highly restricted. In an Android wrapper (TWA/Capacitor), it's possible.
      return false; // Stub
    } catch (e) {
      console.warn('[UPI] SMS verification failed:', e);
      return false;
    }
  }
  return false;
}
